name: Build and release Android apk artifact

on: [push] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Use checkout
        uses: actions/checkout@v1
        
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Use flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
          
      - name: Run pub get
        run: flutter pub get
        working-directory: history_cards_app
      
      - name: Build apk
        run: flutter build apk --debug
        working-directory: history_cards_app
      
      - name: Prepare apk artifact for download
        uses: actions/upload-artifact@v1
        with:
          name: apk-debug.apk
          path: "history_cards_app/build/app/outputs/apk/debug/app-debug.apk"
      
      - name: Create an APK prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "android-latest"
          prerelease: true
          title: "Android APK prerelease"
          files: "history_cards_app/build/app/outputs/apk/debug/app-debug.apk"
